INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 1, 'Nutrition in Plants');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 2, 'Nutrition in Animals');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 3, 'Heat');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 4, 'Acids, Bases and Salts');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 5, 'Physical and Chemical Changes');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 6, 'Respiration in Organisms');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 7, 'Transportation in Animals and Plants');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 8, 'Reproduction in Plants');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 9, 'Motion and Time');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 10, 'Electric Current and its Effects');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 11, 'Light');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 12, 'Forests: Our Lifeline');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SCIENCE', 7, 13, 'Wastewater Story');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 1, 'Integers');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 2, 'Fractions and Decimals');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 3, 'Data Handling');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 4, 'Simple Equations');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 5, 'Lines and Angles');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 6, 'The Triangle and its Properties');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 7, 'Comparing Quantities');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 8, 'Rational Numbers');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 9, 'Perimeter and Area');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 10, 'Algebraic Expressions');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 11, 'Exponents and Powers');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 12, 'Symmetry');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('MATHEMATICS', 7, 13, 'Visualising Solid Shapes');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 1, 'Tracing Changes Through a Thousand Years');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 2, 'New Kings and Kingdoms');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 3, 'The Delhi Sultans');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 4, 'The Mughal Empire');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 5, 'Rulers and Buildings');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 6, 'Towns, Traders and Craftspersons');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 7, 'Tribes, Nomads and Settled Communities');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 8, 'Devotional Paths to the Divine');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 9, 'The Making of Regional Cultures');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SOCIAL SCIENCE', 7, 10, 'Eighteenth-Century Political Formations');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 1, 'The Tiny Teacher');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 2, 'Bringing Up Kari');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 3, 'The Desert');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 4, 'The Cop and the Anthem');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 5, 'Golu Grows a Nose');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 6, 'I Want Something in a Cage');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 7, 'Chandni');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 8, 'The Bear Story');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 9, 'A Tiger in the House');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('ENGLISH', 7, 10, 'An Alien Hand');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 1, 'हम पंछी उन्मुक्त गगन के');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 2, 'दादी माँ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 3, 'हिमालय की बेटियाँ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 4, 'कठपुतली');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 5, 'मिठाईवाला');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 6, 'रक्त और हमारा शरीर');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 7, 'पापा खो गए');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 8, 'शाम – एक किसान');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 9, 'चिड़िया की बच्ची');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 10, 'अपूर्व अनुभव');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 11, 'रहीम के दोहे');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 12, 'कंचा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 13, 'एक तिनका');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 14, 'खानपान की बदलती तसवीर');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 15, 'नीलकंठ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 16, 'भोर और बरखा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 17, 'वीर कुँवर सिंह');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 18, 'संघर्ष के कारण मैं तुनुकमिज़ाज हो गया');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 19, 'आश्रम का अनुमानित व्यय');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('HINDI', 7, 20, 'विप्लव-गायन');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 1, 'सुभाषितानि');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 2, 'दुर्बुद्धिः विनश्यति');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 3, 'स्वावलम्बनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 4, 'हास्यबालकविसम्मेलनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 5, 'पण्डिता रमाबाई');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 6, 'सदाचारः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 7, 'संकल्पः सिद्धिदायकः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 8, 'त्रिवर्णः ध्वजः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 9, 'अहमपि विद्यालयं गमिष्यामि');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 10, 'विश्वबन्धुत्वम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 11, 'समवायो हि दुर्जयः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 12, 'विद्याधनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 13, 'अमृतं संस्कृतम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 14, 'अनारिकायाः जिज्ञासा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('SANSKRIT — Ruchira', 7, 15, 'लालनगीतम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 1, 'Tracing Changes Through a Thousand Years');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 2, 'New Kings and Kingdoms');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 3, 'The Delhi Sultans');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 4, 'The Mughal Empire');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 5, 'Rulers and Buildings');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 6, 'Towns, Traders and Craftspersons');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 7, 'Tribes, Nomads and Settled Communities');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 8, 'Devotional Paths to the Divine');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 9, 'The Making of Regional Cultures');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - History', 7, 10, 'Eighteenth-Century Political Formations');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 1, 'Environment');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 2, 'Inside Our Earth');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 3, 'Our Changing Earth');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 4, 'Air');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 5, 'Water');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 6, 'Human Environment Interactions – The Tropical and Subtropical Region');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Geography', 7, 7, 'Life in the Deserts');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 1, 'On Equality');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 2, 'Role of the Government in Health');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 3, 'How the State Government Works');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 4, 'Growing up as Boys and Girls');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 5, 'Women Change the World');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 6, 'Understanding Media');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 7, 'Markets Around Us');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Civics', 7, 8, 'A Shirt in the Market');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 1, 'हम पंछी उन्मुक्त गगन के');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 2, 'दादी माँ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 3, 'हिमालय की बेटियाँ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 4, 'कठपुतली');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 5, 'मिठाईवाला');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 6, 'रक्त और हमारा शरीर');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 7, 'पापा खो गए');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 8, 'शाम – एक किसान');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 9, 'चिड़िया की बच्ची');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 10, 'अपूर्व अनुभव');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 11, 'रहीम के दोहे');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 12, 'कंचा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 13, 'एक तिनका');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 14, 'खानपान की बदलती तसवीर');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 15, 'नीलकंठ');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 16, 'भोर और बरखा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 17, 'वीर कुँवर सिंह');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 18, 'संघर्ष के कारण मैं तुनुकमिज़ाज हो गया');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 19, 'आश्रम का अनुमानित व्यय');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - An Alien Hand', 7, 20, 'विप्लव-गायन');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 1, 'सुभाषितानि');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 2, 'दुर्बुद्धिः विनश्यति');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 3, 'स्वावलम्बनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 4, 'हास्यबालकविसम्मेलनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 5, 'पण्डिता रमाबाई');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 6, 'सदाचारः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 7, 'संकल्पः सिद्धिदायकः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 8, 'त्रिवर्णः ध्वजः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 9, 'अहमपि विद्यालयं गमिष्यामि');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 10, 'विश्वबन्धुत्वम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 11, 'समवायो हि दुर्जयः');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 12, 'विद्याधनम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 13, 'अमृतं संस्कृतम्');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 14, 'अनारिकायाः जिज्ञासा');
INSERT INTO public.syllabus_chapters (subject_name, class_level, chapter_number, title) VALUES ('Social Science - Durva (18 Chapters', 7, 15, 'लालनगीतम्');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Science', 7, 'Science Textbook Class 7', 'https://ncert.nic.in/textbook/pdf/gesc1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Mathematics', 7, 'Maths Textbook Class 7', 'https://ncert.nic.in/textbook/pdf/gemh1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('History', 7, 'Our Pasts II', 'https://ncert.nic.in/textbook/pdf/gess1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Geography', 7, 'Our Environment', 'https://ncert.nic.in/textbook/pdf/gess2ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Civics', 7, 'Social and Political Life II', 'https://ncert.nic.in/textbook/pdf/gess3ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('English', 7, 'Honeycomb', 'https://ncert.nic.in/textbook/pdf/geeh1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('English', 7, 'An Alien Hand', 'https://ncert.nic.in/textbook/pdf/gesh1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Hindi', 7, 'Vasant', 'https://ncert.nic.in/textbook/pdf/ghvs1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Hindi', 7, 'Durva', 'https://ncert.nic.in/textbook/pdf/ghdr1ps.pdf');
INSERT INTO public.subject_resources (subject_name, class_level, title, url) VALUES ('Sanskrit', 7, 'Ruchira', 'https://ncert.nic.in/textbook/pdf/gskr1ps.pdf');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which part of the plant makes food using sunlight?', 'Root', 'Stem', 'Leaf', 'Flower', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The process by which green plants make their own food is called:', 'Respiration', 'Photosynthesis', 'Digestion', 'Transpiration', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which organism is an example of a saprophyte?', 'Cactus', 'Mushroom', 'Mango tree', 'Fern', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Amoeba digests food in a structure called:', 'Stomach', 'Cell wall', 'Food vacuole', 'Nucleus', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The SI unit of temperature is:', 'Celsius', 'Fahrenheit', 'Kelvin', 'Joule', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which of the following is an acid?', 'Baking soda', 'Lemon juice', 'Soap', 'Chalk', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Rusting of iron is a:', 'Physical change', 'Reversible change', 'Chemical change', 'No change', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which gas is released during respiration?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The liquid part of blood is called:', 'Plasma', 'Platelets', 'Haemoglobin', 'Serum', 'A', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Reproduction in plants by seeds is called:', 'Vegetative reproduction', 'Sexual reproduction', 'Budding', 'Fragmentation', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The unit of speed is:', 'km', 'm/s', 'kg', 'Newton', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which component of electric circuit controls current flow?', 'Wire', 'Switch', 'Bulb', 'Battery', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'A convex mirror is used in:', 'Rear-view mirrors', 'Torches', 'Telescopes', 'Periscopes', 'A', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Forests help in maintaining:', 'Temperature only', 'Water cycle only', 'Both water cycle and oxygen levels', 'Soil erosion only', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which microorganism converts milk into curd?', 'Yeast', 'Bacteria', 'Fungus', 'Algae', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The process by which water vapour is released by leaves is called:', 'Photosynthesis', 'Transpiration', 'Respiration', 'Absorption', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Wastewater treatment removes:', 'Only odour', 'Only colour', 'Harmful substances and microbes', 'Only solids', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Plants that obtain nutrients from insects are called:', 'Parasites', 'Saprotrophic', 'Insectivorous', 'Symbiotic', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'Which of these is a chemical change?', 'Melting of ice', 'Cutting paper', 'Burning of wood', 'Dissolving salt', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('SCIENCE', 7, 'The speed of light is approximately:', '3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁴ m/s', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'What is (–7) + (–3)?', '10', '–10', '4', '–4', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'What is 2/3 × 3/4?', '1/2', '6/7', '2/4', '1/3', 'A', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'The mean of 4, 8, 6, 10, 2 is:', '5', '6', '7', '8', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'If 2x + 3 = 11, then x = ?', '3', '4', '5', '6', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'The sum of angles in a triangle is:', '90°', '180°', '270°', '360°', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'An equilateral triangle has all sides:', 'Unequal', 'Two equal', 'All equal', 'No equal', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'What is 15% of 200?', '20', '25', '30', '35', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'Which of the following is a rational number?', '√2', 'π', '3/4', '√3', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'Area of a rectangle with length 8 cm and breadth 5 cm is:', '13 cm²', '26 cm²', '40 cm²', '80 cm²', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'Simplify: 3x + 2x', '5x', '6x', 'x', '5x²', 'A', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, '2³ × 2² = ?', '2⁵', '2⁶', '4⁵', '2¹', 'A', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'A line of symmetry divides a figure into:', 'Two unequal parts', 'Two identical parts', 'Three parts', 'Four parts', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'A cube has how many faces?', '4', '6', '8', '12', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'What is (–5) × (–3)?', '–15', '15', '–8', '8', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'The mode of 2, 3, 3, 4, 5, 3 is:', '2', '3', '4', '5', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'Perimeter of a square with side 7 cm is:', '14 cm', '21 cm', '28 cm', '49 cm', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'Which of these is NOT a rational number?', '1/3', '0', '√5', '–7', 'C', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'If the ratio of boys to girls is 3:2 and there are 30 boys, how many girls?', '15', '20', '25', '10', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, '10⁰ = ?', '0', '1', '10', '100', 'B', '');
INSERT INTO public.mcq_questions (subject_name, class_level, question, option_a, option_b, option_c, option_d, correct_answer, source) VALUES ('MATHEMATICS', 7, 'A bar graph is used to represent:', 'Continuous data', 'Categorical data', 'Fractions only', 'Decimals only', 'B', '');
